# Generated by Django 5.0.1 on 2024-02-12 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('year', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, default='Пользователь не найден', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='comment_user', to=settings.AUTH_USER_MODEL, verbose_name='Автор коментария')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default='Пользователь не найден', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='answer_user', to=settings.AUTH_USER_MODEL, verbose_name='Автор ответа')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='Change.comments', verbose_name='Комент')),
            ],
        ),
        migrations.CreateModel(
            name='GameGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Change.game')),
            ],
        ),
        migrations.CreateModel(
            name='GamePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Change.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_platform',
            field=models.ManyToManyField(blank=True, through='Change.GamePlatform', to='Change.game'),
        ),
        migrations.CreateModel(
            name='GameTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Change.game')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Текст объявления')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('text', models.TextField()),
                ('isPublished', models.BooleanField(default=False)),
                ('just_sell', models.BooleanField(default=False)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('goods_desired_games', models.ManyToManyField(blank=True, related_name='desired', through='Change.GameGoods', to='Change.game')),
                ('goods_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Change.game', verbose_name='Игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Опубликовал')),
            ],
        ),
        migrations.AddField(
            model_name='gamegoods',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Change.goods'),
        ),
        migrations.AddField(
            model_name='game',
            name='desired_games',
            field=models.ManyToManyField(blank=True, through='Change.GameGoods', to='Change.goods'),
        ),
        migrations.AddField(
            model_name='comments',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good', to='Change.goods', verbose_name='Товар'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('isRead', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='Change.chat', verbose_name='Чат')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('pic', models.ImageField(blank=True, upload_to='platform/pics/%Y/%m/%d')),
                ('game', models.ManyToManyField(blank=True, related_name='platform', through='Change.GamePlatform', to='Change.game')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Change.platform', verbose_name='Платформа'),
        ),
        migrations.AddField(
            model_name='gameplatform',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Change.platform'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default='Пользователь не найден', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва')),
                ('rewuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewuser', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, которому оставили отзыв')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('game', models.ManyToManyField(blank=True, related_name='tag', through='Change.GameTags', to='Change.game')),
            ],
        ),
        migrations.AddField(
            model_name='gametags',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Change.tags'),
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag', through='Change.GameTags', to='Change.tags'),
        ),
    ]
